apiVersion: storage.dell.com/v1
kind: ContainerStorageModule
metadata:
  name: isilon
  namespace: isilon
spec:
  driver:
    csiDriverType: "isilon"
    configVersion: v2.15.1
    authSecret: isilon-creds
    common:
      envs:
        - name: X_CSI_ISI_AUTH_TYPE
          value: "1"
