apiVersion: v1
kind: Pod
metadata:
  name: pod-isilon
  namespace: default
spec:
  containers:
  - name: ubi
    image: registry.access.redhat.com/ubi9/ubi
    command: [ "bash", "-c" ]
    args: [ "while true; do touch /data/file-$(date +%s); sleep 20; done;" ]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pvc-isilon
