apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-isilon
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: isilon
